###### Generar token usuario valido
POST http://localhost:3000/usuarios/autorizar HTTP/1.1
Content-Type: application/json

{
    "correo": "admin@demo.com",
    "password": "1233123"
}

### Crear usuario
POST http://localhost:3000/usuarios/crearusuario HTTP/1.1
content-type: application/json

{
    "correo": "admin@demo.com",
    "password": "1233123",
    "rol": 1
}
